# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "make build"
  bin = "tmp/server" 
  include_ext = ["go", "tpl", "tmpl", "templ", "html"]
  exclude_dir = ["tmp", "vendor"]
  follow_symlink = true
  kill_delay = "0s"
  exclude_regex = [".*_templ\\.go$"]

[proxy]
  enabled = true
  proxy_port = 3030
  app_port = 3000

[log]
  time = true
